### ISSUE TITLE
New Tauri Version

### ISSUE THREAD

**Issue by MoYuan-CN** [PCL-Community/PCL2-LogViewer#2]
看不下去 eLang 了

**Comment by Deep-Dark-Forest** [comment]
有没有一种可能，am他不会前端…

**Comment by MoYuan-CN** [comment]
哈哈哈

**Comment by MoYuan-CN** [comment]
转 [PCL-Community/PCL2-LogViewer-TE](https://github.com/PCL-Community/PCL2-LogViewer-TE) 仓库
